name: template-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.4=hbcca054_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgomp=14.1.0=h77fa898_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.3.1=h4bc722e_2
  - pip=24.2=pyhd8ed1ab_0
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - asgiref==3.8.1
      - blinker==1.8.2
      - certifi==2024.7.4
      - click==8.1.7
      - django==5.1
      - environs==11.0.0
      - flask==3.0.3
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - packaging==24.1
      - python-dotenv==1.0.1
      - sqlparse==0.5.1
      - werkzeug==3.0.3
prefix: /home/mly/miniconda3/envs/template-env
